### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by alexandrucancescu** [sindresorhus/run-applescript#11]
You probably forgot to add the typescript files to npm.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/run-applescript/blob/dd9465af64f36e7775180997a20af0671ace43cd/package.json#L18-L21

This is most likely a problem on your side.

**Comment by alexandrucancescu** [comment]
Sorry to bother you, webstorm installed an older version without the definition file.
