### ISSUE TITLE
Cannot read property 'signals' of undefined

### ISSUE THREAD

**Issue by castroCrea** [sindresorhus/run-applescript#12]
Hello I update from 4.0.0 to 5.0.0 and I got this error 
![image](https://user-images.githubusercontent.com/20707343/113124987-69fc2480-9216-11eb-978e-1442e4ef320e.png)

any clue ?

**Comment by sindresorhus** [comment]
The error is not coming from this package. If you use a bundler like Webpack, the problem is definitely Webpack or your Webpack configuration.
